name: Production Deployment

on:
  release:
    types: [published]

jobs:
  deploy_production:
    name: Deploy Production
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ vars.DOMAIN_URL }}
    
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Sync Environment Variables
        run: |
          vercel env add TICKETMASTER_KEY production --force --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ secrets.VERCEL_ORG_ID }}
          vercel env add GOOGLE_MAPS_API_KEY production --force --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ secrets.VERCEL_ORG_ID }}
          vercel env add BASE_URL production --force --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ secrets.VERCEL_ORG_ID }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Deploy Project to Vercel
        run: vercel deploy --prod --yes

      - name: Success
        run: echo "🚀 Deploy successful 🚀 "